apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-dotnet-basic-giobkktx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-dotnet-basic-giobkktx 
  name: backend-tests-dotnet-basic-giobkktx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-dotnet-basic-giobkktx 
